apiVersion: v1
kind: Namespace
metadata:
  name: a3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: a3pvc
  namespace: a3
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: a3
data:
  FILE_PATH: /PV_dir/
  PARSER_APP_URI: http://container2.a3

---
apiVersion: v1
kind: Service
metadata:
  name: container1
  namespace: a3
spec:
  selector:
    app: container1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
  namespace: a3
spec:
  selector:
    matchLabels:
      app: container1
  replicas: 1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: northamerica-northeast1-docker.pkg.dev/cloud-390101/cloud/container1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          envFrom:
            - configMapRef:
                name: config
          volumeMounts:
            - mountPath: /PV_dir
              name: c2pvc
      volumes:
        - name: c2pvc
          persistentVolumeClaim:
            claimName: a3pvc
