
---
apiVersion: v1
kind: Service
metadata:
  name: container2
  namespace: a3
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: container2
  namespace: a3
spec:
  selector:
    matchLabels:
      app: container2
  replicas: 1
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: northamerica-northeast1-docker.pkg.dev/cloud-390101/cloud/container2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
          envFrom:
            - configMapRef:
                name: config
          volumeMounts:
            - mountPath: /PV_dir
              name: c2pvc
      volumes:
        - name: c2pvc
          persistentVolumeClaim:
            claimName: a3pvc
